USE DATABASE DATAENGINEERING;

USE SCHEMA SOURCE;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE STORAGE INTEGRATION AZURESNOWBATCH
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER=AZURE
ENABLED=TRUE
AZURE_TENANT_ID='e18e8ddf-4cdd-4c0d-86e9-af9546b5441f'
STORAGE_ALLOWED_LOCATIONS=('azure://santhoshdbtaccount.blob.core.windows.net/snowflakebatch')

DESCRIBE INTEGRATION AZURESNOWBATCH

CREATE OR REPLACE FILE FORMAT CSVFORMAT
TYPE='CSV'
FIELD_DELIMITER=','
RECORD_DELIMITER='\n'
SKIP_HEADER=1

CREATE OR REPLACE STAGE STAGESNOWBATCH
STORAGE_INTEGRATION=AZURESNOWBATCH
FILE_FORMAT=CSVFORMAT
URL='azure://santhoshdbtaccount.blob.core.windows.net/snowflakebatch/source/booking/'

LIST @STAGESNOWBATCH