SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'CUSTOMERS',
        START_TIME => DATEADD(DAY, -7, CURRENT_TIMESTAMP())
    )
);

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
ORDER BY LAST_LOAD_TIME DESC;   


SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
WHERE TABLE_NAME = 'CUSTOMERS'
ORDER BY LAST_LOAD_TIME DESC;



SELECT *
FROM TABLE(
    VALIDATE(
        TABLE_NAME => 'CUSTOMERS',
        JOB_ID => '_last'
    )
);

//validate is not a informatin schema