--*What happened to the files?
SELECT FILE_NAME,
    LAST_LOAD_TIME,STATUS,
    ROW_COUNT,
    ERROR_COUNT,
    FIRST_ERROR_MESSAGE
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'DATAENGINEERING.SOURCE.BOOKINGS',
        START_TIME => DATEADD('HOUR', -24, CURRENT_TIMESTAMP()),
        PIPE_NAME  => 'DATAENGINEERING.SOURCE.SNOWPIPE'
    )
)
ORDER BY LAST_LOAD_TIME DESC;