SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.LOGIN_HISTORY(
        TIME_RANGE_START => DATEADD(DAY, -7, CURRENT_TIMESTAMP())
    )
);


SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.LOGIN_HISTORY_BY_USER(
        USER_NAME => 'SANTHOSH'
    )
);


SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
ORDER BY EVENT_TIMESTAMP DESC;


