SELECT
    PIPE_NAME,
    SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
GROUP BY PIPE_NAME
ORDER BY TOTAL_CREDITS DESC;


SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
        PIPE_NAME => 'CUSTOMER_PIPE'
    )
);

