SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.WAREHOUSE_METERING_HISTORY(
        DATE_RANGE_START => DATEADD(DAY,-30,CURRENT_TIMESTAMP()),
        WAREHOUSE_NAME => 'COMPUTE_WH'
    )
);


//Provides up to **365 days** of warehouse metering history. 【2-f6aff6】

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
ORDER BY START_TIME DESC;


SELECT
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_CREDITS DESC;
```【2-f6aff6】

---

## Compute vs Cloud Services Credits

```sql
SELECT
    WAREHOUSE_NAME,
    SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICE_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY WAREHOUSE_NAME;
```【2-f6aff6】

---


SELECT
    DATE(START_TIME) AS USAGE_DATE,
    SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY DATE(START_TIME)
ORDER BY USAGE_DATE DESC;


SELECT
    WAREHOUSE_NAME,
    SUM(CREDITS_USED_COMPUTE)
      - SUM(CREDITS_ATTRIBUTED_COMPUTE_QUERIES) AS IDLE_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY WAREHOUSE_NAME
ORDER BY IDLE_CREDITS DESC;
