CREATE OR REPLACE PROCEDURE INPUT_PARAMETER(NUMBER1 INTEGER, NUMBER2 INTEGER)
RETURNS INTEGER
LANGUAGE SQL
AS
$$
DECLARE
TOTAL INTEGER DEFAULT 0;
BEGIN
TOTAL := NUMBER1+NUMBER2;
RETURN TOTAL;
END;
$$;

CREATE OR REPLACE PROCEDURE INPUT_PARAMETER(NUMBER1 INTEGER, NUMBER2 INTEGER)
RETURNS INTEGER
LANGUAGE SQL
AS
$$
BEGIN
    RETURN NUMBER1 + NUMBER2;
END;
$$;

CREATE OR REPLACE PROCEDURE SELECT_INTO()
RETURNS INTEGER
LANGUAGE SQL
AS
$$
DECLARE
ROW_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO :ROW_COUNT FROM LISTINGS;
RETURN ROW_COUNT;
END;
$$


CALL SELECT_INTO()

CALL INPUT_PARAMETER(10,20);

SHOW PROCEDURES LIKE 'INPUT_PARAMETER';

CREATE OR REPLACE PROCEDURE INSERT_INTO(ID INTEGER, NAME VARCHAR, PHONE INTEGER)
RETURNS TABLE(
ID INTEGER, NAME VARCHAR, PHONE INTEGER)
LANGUAGE SQL
AS 
$$
DECLARE
RESULT_SET RESULTSET;
BEGIN
INSERT INTO STUDENT VALUES(:ID,:NAME,:PHONE);
RESULT_SET :=(SELECT * FROM STUDENT);
RETURN RESULT_SET;
END;
$$

-- CREATE OR REPLACE TABLE STUDENT(
-- ID INTEGER,
-- NAME VARCHAR,
-- PHONE INTEGER
-- )