CREATE TAG GOVERNANCE.TAGS.ENVIRONMENT
    ALLOWED_VALUES 'DEV', 'TEST', 'PROD';

CREATE TAG GOVERNANCE.TAGS.DEPARTMENT
    ALLOWED_VALUES 'SALES', 'FINANCE', 'HR', 'IT';

CREATE TAG GOVERNANCE.TAGS.DATA_CLASSIFICATION
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED';


    

CREATE DATABASE IF NOT EXISTS SALES_DB
    DATA_RETENTION_TIME_IN_DAYS = 7
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 14
    DEFAULT_DDL_COLLATION = 'en-ci'
    COMMENT = 'Production database for sales workloads'
    WITH TAG (
        GOVERNANCE_DB.TAGS.ENVIRONMENT = 'PROD',
        GOVERNANCE_DB.TAGS.DEPARTMENT = 'SALES',
        GOVERNANCE_DB.TAGS.DATA_CLASSIFICATION = 'CONFIDENTIAL',
        GOVERNANCE_DB.TAGS.COST_CENTER = 'CC100',
        GOVERNANCE_DB.TAGS.OWNER = 'DATA_ENGINEERING'
    );



    CREATE SCHEMA IF NOT EXISTS SALES_DB
    with managed access
    DATA_RETENTION_TIME_IN_DAYS = 7
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 14
    DEFAULT_DDL_COLLATION = 'en-ci'
    COMMENT = 'Production database for sales workloads'
    WITH TAG (
        GOVERNANCE_DB.TAGS.ENVIRONMENT = 'PROD',
        GOVERNANCE_DB.TAGS.DEPARTMENT = 'SALES',
        GOVERNANCE_DB.TAGS.DATA_CLASSIFICATION = 'CONFIDENTIAL',
        GOVERNANCE_DB.TAGS.COST_CENTER = 'CC100',
        GOVERNANCE_DB.TAGS.OWNER = 'DATA_ENGINEERING'
    );