CREATE RESOURCE MONITOR MONTHLY_MONITOR
WITH
    CREDIT_QUOTA = 100
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY -- specify timestamp
    END_TIMESTAMP = '2026-12-31 23:59:59'
    NOTIFY_USERS = (USER1, USER2)
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;


-- Frequency options

-- DAILY
-- WEEKLY
-- MONTHLY
-- YEARLY
-- NEVER

