CREATE SEMANTIC VIEW SALES_DB.SALES.SALES_ANALYTICS

TABLES (
    ORDERS AS SALES_DB.SALES.ORDERS
        PRIMARY KEY (ORDER_ID),

    CUSTOMERS AS SALES_DB.SALES.CUSTOMERS
        PRIMARY KEY (CUSTOMER_ID)
)

RELATIONSHIPS (
    ORDERS_TO_CUSTOMERS AS
        ORDERS (CUSTOMER_ID)
        REFERENCES CUSTOMERS
)

FACTS (
    ORDERS.ORDER_AMOUNT AS ORDER_AMOUNT,
    ORDERS.LINE_AMOUNT AS QUANTITY * UNIT_PRICE
)

DIMENSIONS (
    ORDERS.ORDER_DATE AS ORDER_DATE,
    ORDERS.ORDER_STATUS AS ORDER_STATUS,
    CUSTOMERS.REGION AS REGION
)

METRICS (
    ORDERS.TOTAL_REVENUE AS SUM(ORDERS.ORDER_AMOUNT),
    ORDERS.ORDER_COUNT AS COUNT(ORDERS.ORDER_ID),
    ORDERS.AVERAGE_ORDER_VALUE AS AVG(ORDERS.ORDER_AMOUNT)
)

COMMENT = 'Business semantic layer for sales analytics';

------------------how to query it -------------------------

SELECT *
FROM SEMANTIC_VIEW(
    SALES_DB.SALES.SALES_ANALYTICS
    METRICS ORDERS.TOTAL_REVENUE
    DIMENSIONS CUSTOMERS.REGION
);


SELECT *
FROM SEMANTIC_VIEW(
    SALES_DB.SALES.SALES_ANALYTICS
    METRICS ORDERS.TOTAL_REVENUE
    DIMENSIONS CUSTOMERS.REGION
    WHERE ORDERS.ORDER_STATUS = 'COMPLETED'
);


CREATE SEQUENCE NOORDER_SEQ
    START = 1
    INCREMENT = 1
    NOORDER;

CREATE SEQUENCE NOORDER_SEQ
    START = 1
    INCREMENT = 1
    ORDER;

 -- how to access noorder_seq.nextval -- will generate new values but not gap free

 
