-- scalar UDF
-- User Defined Table FUNCTION
-- user Defined Aggregate function


CREATE OR REPLACE FUNCTION SALES_DB.UTILS.CALCULATE_TAX(
    AMOUNT NUMBER,
    TAX_PERCENTAGE NUMBER
)
RETURNS NUMBER
LANGUAGE SQL
RETURNS NULL ON NULL INPUT
AS
$$
    AMOUNT * TAX_PERCENTAGE / 100
$$;