
CREATE WAREHOUSE ETL_WH
WITH
    WAREHOUSE_SIZE = LARGE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'ETL Processing Warehouse';
    
-- The most important warehouse creation options you should know are:

-- WAREHOUSE_SIZE
-- WAREHOUSE_TYPE
-- MIN_CLUSTER_COUNT
-- MAX_CLUSTER_COUNT
-- SCALING_POLICY
-- AUTO_SUSPEND
-- AUTO_RESUME
-- RESOURCE_MONITOR
-- ENABLE_QUERY_ACCELERATION
-- MAX_CONCURRENCY_LEVEL


-- 1. warehouse size

-- XSMALL
-- SMALL
-- MEDIUM
-- LARGE
-- XLARGE
-- XXLARGE
-- XXXLARGE
-- X4LARGE
-- X5LARGE
-- X6LARGE

-- 2. Warehouse TYPE

-- STANDARD (default)
-- SNOWPARK-OPTIMIZED
-- ADAPTIVE

-- 3. Scaling POLICY

-- Standard
-- Economy

-- 4. STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300

-- 5. STATEMENT_TIMEOUT_IN_SECONDS = 3600
